name = "color-shift-reactor"
compatibility_date = "2024-03-20"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "LB_KV"
id = "f48ab3d8c99749e4a1612bbc335e97a9"
preview_id = "f48ab3d8c99749e4a1612bbc335e97a9"

[vars]
# Add to .dev.vars for local dev:
# GOOGLE_CLIENT_ID="your-google-client-id"
